#include <stdint.h>
typedef enum Ps4 : int8_t{ 
    DPAD,

    BUTTON_SQUARE,
    BUTTON_CROSS ,
    BUTTON_CIRCLE,  
    BUTTON_TRIANGLE,

    BUTTON_LEFT_SHOULDER,
    BUTTON_RIGHT_SHOULDER,

    BUTTON_LEFT_TRIGGER,
    BUTTON_RIGHT_TRIGGER,

    BUTTON_LEFT_JOYSTICK,
    BUTTON_RIGHT_JOYSTICK,

    BUTTON_SHARE,
    STICK_LEFT_X ,
    STICK_LEFT_Y ,
    STICK_RIGHT_X ,
    STICK_RIGHT_Y ,

    GYRO_X ,
    GYRO_Y ,
    GYRO_Z ,

    ACCEL_X ,
    ACCEL_Y ,
    ACCEL_Z ,

    RUMBLE,
    LED_GREEN,
    LED_RED,
    LED_BLUE,

} Ps4;